name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - run: docker run --name mysql -e MYSQL_ROOT_PASSWORD=P@ssw0rd -v $(pwd):/scripts -d mysql:latest
    # - run: npm test
    # - name: Upload HTML report(backstop data)
    #   if: ${{ always() }}
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: report
    #     path: backstop_data